# Generated by Django 5.0.2 on 2024-03-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='location',
            field=models.TextField(default='Movement Columbia'),
            preserve_default=False,
        ),
    ]
