# Generated by Django 5.0.2 on 2024-03-21 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_class_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['start_time']},
        ),
    ]
