# Generated by Django 5.0.2 on 2024-03-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_class_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
