# Generated by Django 5.0.2 on 2024-03-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_class_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
