/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StackerRouteImport } from './routes/stacker'
import { Route as CanvasRouteImport } from './routes/_canvas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesArticleRouteImport } from './routes/articles.$article'
import { Route as CanvasMeleeRouteImport } from './routes/_canvas.melee'
import { Route as CanvasExperienceRouteImport } from './routes/_canvas.experience'
import { Route as CanvasClimbingRouteImport } from './routes/_canvas.climbing'
import { Route as CanvasArticlesRouteImport } from './routes/_canvas.articles'
import { Route as CanvasAboutRouteImport } from './routes/_canvas.about'

const StackerRoute = StackerRouteImport.update({
  id: '/stacker',
  path: '/stacker',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/_canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleRoute = ArticlesArticleRouteImport.update({
  id: '/articles/$article',
  path: '/articles/$article',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasMeleeRoute = CanvasMeleeRouteImport.update({
  id: '/melee',
  path: '/melee',
  getParentRoute: () => CanvasRoute,
} as any)
const CanvasExperienceRoute = CanvasExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => CanvasRoute,
} as any)
const CanvasClimbingRoute = CanvasClimbingRouteImport.update({
  id: '/climbing',
  path: '/climbing',
  getParentRoute: () => CanvasRoute,
} as any)
const CanvasArticlesRoute = CanvasArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => CanvasRoute,
} as any)
const CanvasAboutRoute = CanvasAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => CanvasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stacker': typeof StackerRoute
  '/about': typeof CanvasAboutRoute
  '/articles': typeof CanvasArticlesRoute
  '/climbing': typeof CanvasClimbingRoute
  '/experience': typeof CanvasExperienceRoute
  '/melee': typeof CanvasMeleeRoute
  '/articles/$article': typeof ArticlesArticleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stacker': typeof StackerRoute
  '/about': typeof CanvasAboutRoute
  '/articles': typeof CanvasArticlesRoute
  '/climbing': typeof CanvasClimbingRoute
  '/experience': typeof CanvasExperienceRoute
  '/melee': typeof CanvasMeleeRoute
  '/articles/$article': typeof ArticlesArticleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_canvas': typeof CanvasRouteWithChildren
  '/stacker': typeof StackerRoute
  '/_canvas/about': typeof CanvasAboutRoute
  '/_canvas/articles': typeof CanvasArticlesRoute
  '/_canvas/climbing': typeof CanvasClimbingRoute
  '/_canvas/experience': typeof CanvasExperienceRoute
  '/_canvas/melee': typeof CanvasMeleeRoute
  '/articles/$article': typeof ArticlesArticleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stacker'
    | '/about'
    | '/articles'
    | '/climbing'
    | '/experience'
    | '/melee'
    | '/articles/$article'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stacker'
    | '/about'
    | '/articles'
    | '/climbing'
    | '/experience'
    | '/melee'
    | '/articles/$article'
  id:
    | '__root__'
    | '/'
    | '/_canvas'
    | '/stacker'
    | '/_canvas/about'
    | '/_canvas/articles'
    | '/_canvas/climbing'
    | '/_canvas/experience'
    | '/_canvas/melee'
    | '/articles/$article'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanvasRoute: typeof CanvasRouteWithChildren
  StackerRoute: typeof StackerRoute
  ArticlesArticleRoute: typeof ArticlesArticleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stacker': {
      id: '/stacker'
      path: '/stacker'
      fullPath: '/stacker'
      preLoaderRoute: typeof StackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_canvas': {
      id: '/_canvas'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$article': {
      id: '/articles/$article'
      path: '/articles/$article'
      fullPath: '/articles/$article'
      preLoaderRoute: typeof ArticlesArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_canvas/melee': {
      id: '/_canvas/melee'
      path: '/melee'
      fullPath: '/melee'
      preLoaderRoute: typeof CanvasMeleeRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/_canvas/experience': {
      id: '/_canvas/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof CanvasExperienceRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/_canvas/climbing': {
      id: '/_canvas/climbing'
      path: '/climbing'
      fullPath: '/climbing'
      preLoaderRoute: typeof CanvasClimbingRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/_canvas/articles': {
      id: '/_canvas/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof CanvasArticlesRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/_canvas/about': {
      id: '/_canvas/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof CanvasAboutRouteImport
      parentRoute: typeof CanvasRoute
    }
  }
}

interface CanvasRouteChildren {
  CanvasAboutRoute: typeof CanvasAboutRoute
  CanvasArticlesRoute: typeof CanvasArticlesRoute
  CanvasClimbingRoute: typeof CanvasClimbingRoute
  CanvasExperienceRoute: typeof CanvasExperienceRoute
  CanvasMeleeRoute: typeof CanvasMeleeRoute
}

const CanvasRouteChildren: CanvasRouteChildren = {
  CanvasAboutRoute: CanvasAboutRoute,
  CanvasArticlesRoute: CanvasArticlesRoute,
  CanvasClimbingRoute: CanvasClimbingRoute,
  CanvasExperienceRoute: CanvasExperienceRoute,
  CanvasMeleeRoute: CanvasMeleeRoute,
}

const CanvasRouteWithChildren =
  CanvasRoute._addFileChildren(CanvasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanvasRoute: CanvasRouteWithChildren,
  StackerRoute: StackerRoute,
  ArticlesArticleRoute: ArticlesArticleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
