service: django-aws-lambda

plugins:
  - serverless-prune-plugin
  - serverless-python-requirements
  - serverless-wsgi
useDotenv: true

custom:
  dotenv:
    logging: false
  pythonRequirements:
    dockerizePip: non-linux
    zip: true
    fileName: pyproject.toml
  stage: ${env:STAGE, 'default'}
  wsgi:
    app: django_aws_lambda.wsgi.application
    packRequirements: false
  prune:
    automatic: true
    number: 3

functions:
  - app:
      handler: wsgi_handler.handler
      events:
        - http: ANY /
        - http: ANY /{proxy+}
      timeout: 30

provider:
  name: aws
  iam:
    role: arn:aws:iam::928394170560:user/admin
  profile: admin
  region: us-east-1
  runtime: python3.8
  versionFunctions: false
  stage: ${env:STAGE, 'default'}
  timeout: 60
  vpc:
    securityGroupIds:
      - sg-08103547
    subnetIds:
      - subnet-7e1b8a55
      - subnet-110b124b
      - subnet-e74d439e
      - subnet-d9a18992
  apiGateway:
    shouldStartNameWithService: true

package:
  individually: true
  exclude:
    - .cache/**
    - .env
    - .git/**
    - .github/**
    - .pytest_cache/**
    - .serverless/**
    - node_modules/**
    - static/**
    - db.sqlite3
