# Cloud Build configuration for automatic deployments
#
# Environment variables are read from:
# 1. Cloud Build trigger substitution variables (set in GCP Console)
# 2. Secret Manager (for sensitive data)
#
# Setup:
# 1. Store secrets in Secret Manager:
#    gcloud secrets create VITE_GA_TRACKING_ID --data-file=- <<< "your-ga-id"
#
# 2. Grant Cloud Build access to secrets:
#    PROJECT_NUMBER=$(gcloud projects describe $PROJECT_ID --format='value(projectNumber)')
#    gcloud secrets add-iam-policy-binding VITE_GA_TRACKING_ID \
#      --member="serviceAccount:${PROJECT_NUMBER}@cloudbuild.gserviceaccount.com" \
#      --role="roles/secretmanager.secretAccessor"
#
# 3. Set non-secret substitutions in Cloud Build trigger settings

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/VITE_GA_TRACKING_ID/versions/latest
      env: 'GA_TRACKING_ID'

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/r2dliu-website:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/r2dliu-website:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/r2dliu-website:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/r2dliu-website:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    secretEnv: ['GA_TRACKING_ID']
    args:
      - 'run'
      - 'deploy'
      - 'r2dliu-website'
      - '--image'
      - 'gcr.io/$PROJECT_ID/r2dliu-website:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'VITE_API_URL=${_API_URL},VITE_GA_TRACKING_ID=$$GA_TRACKING_ID'

# Default substitution values (override these in Cloud Build trigger settings)
substitutions:
  _API_URL: 'https://api.r2dliu.com'
  _REGION: 'us-central1'

images:
  - 'gcr.io/$PROJECT_ID/r2dliu-website:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/r2dliu-website:latest'
